### ISSUE TITLE
[GPT-30] Search: Modal is not responsive on mobile

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#250]
1. I think there needs to be some more changes made to ensure the search feature is responsive on mobile:

![image.png](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/bbf8e11f-82c6-49ed-bc03-f2f64e678c21/1dccbb1b-945d-4acb-ad22-86e5900c9e67)

2. Longer post titles are not handled well:

![image.png](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/10f3c0da-4a57-429f-b15d-88f5ad41a1c6/17eab2a7-fa30-46f1-9026-7a0c91f2d1e3)

3. Pages with no excerpts look a bit odd:

![image.png](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/572124e5-a89a-4ad1-8509-3c11d09368ad/c2ad02d5-9a07-48a3-be36-7e2982a14150)

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-30](https://linear.app/advisorysg/issue/GPT-30/search-modal-is-not-responsive-on-mobile)</sub>

<img width="666" alt="image" src="https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/b2fc4a7e-b05f-41e4-b939-d0b5b1f55e2d">

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/23a223ed-0558-489d-a261-687ef2e30088)

**Comment by Hackin7** [comment]
Part of the reason this issue exists is the fixed height of the search entry & increased size of text, which can be found in `assets/css/site/search.css` of `.search-result-row-link`. I think the initial idea of this is to make it easy to fit a fixed number of entries per page for pagination.

Some things to take note of
1. the padding of the entry is also a bit off (bottom padding very small/ nonexistent) due to the overflow.

Potential solutions
1. Increase the height per search entry? (This would worsen the 3rd point though, but for that we could put placeholder text instead eg. `Includes content related to <Press Releases>`.
2. Reducing padding may partially solve the issue too
